### ISSUE TITLE
multithreading questions

### ISSUE THREAD

**Issue by divinity76** [acozzette/BUSE#10]
didn't know where else to ask, but it's not clear to me, 
do i have to account for the possibility of several threads calling 
any combination of buse_operations.write / buse_operations.read at the same time? or will only 1 instance of those functions be ran at any given time? (important for instance if i have a static buffer area for writes)

**Comment by bandi13** [comment]
It's one at a time. There's no multithreading in this version. Request comes in via NBD, it gets sent to the write/read operation, then reply sent back to NBD. Same goes for my CPP version ([https://github.com/bandi13/BUSE-CPP](url)).

You could add multithreading if you wanted by reading requests from NBD until there's nothing left to read or there's something ready to reply, but you'll have to make sure that you send the replies in the order the requests came in.

**Comment by divinity76** [comment]
thank you :)
